version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DB=$MONGO_DB
    volumes:
      - .:/usr/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    ports:
      - "3333:3333"
    command: yarn dev

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
